### ISSUE TITLE
Links to annotations point to wrong address

### ISSUE THREAD

**Issue by Sija** [crystal-ameba/github-action#6]
![image](https://user-images.githubusercontent.com/988/70289501-369db700-17d5-11ea-8581-51c61a4bfdde.png)

Clicking on `Check warning on line ...` link leads to `/commit/<commit-sha>#annotation_<id>`, where there's neither the request file nor annotation nowhere to be found.

**Comment by veelenga** [comment]
This action inspects a hole project (not the change) and adds an annotation to a specific commit. Since your linting issue is not a part of that change (is was introduced in some commit before), GitHub doesn't show the annotation as part of a linked commit. 

I will have to think about some solutions, but it looks like there is no good way to handle it.

**Comment by jsg2021** [comment]
Is there no tree view of the commit we can link to?

**Comment by jsg2021** [comment]
sorry wrong repo.
